/*
 * AnnotationPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.components;

import javax.swing.*;

import sbrn.mapviewer.data.*;
import sbrn.mapviewer.gui.*;

/**
 *
 * @author  __USER__
 */
public class AnnotationPanel extends javax.swing.JPanel
{
	MapSet mapSet;
	
	/** Creates new form AnnotationPanel */
	public AnnotationPanel(MapSet mapSet)
	{
		this.mapSet = mapSet;
		initComponents();
		setBackground(Colors.backgroundGradientEndColour);
		setInitialText();
	}
	
	private void setInitialText()
	{
		genomeInfo.setText(mapSet.getName());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		genomeInfo = new javax.swing.JLabel();
		
		setBackground(new java.awt.Color(255, 255, 255));
		
		genomeInfo.setFont(new java.awt.Font("Tahoma", 1, 13));
		genomeInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		genomeInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										genomeInfo,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										256, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										genomeInfo,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										11, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel genomeInfo;
	// End of variables declaration//GEN-END:variables
	
}
