/*
 * FoundFeaturesTableControlPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.components;

import sbrn.mapviewer.gui.*;

/**
 *
 * @author  __USER__
 */
public class FoundFeaturesTableControlPanel extends javax.swing.JPanel
{
	
	/** Creates new form FoundFeaturesTableControlPanel */
	public FoundFeaturesTableControlPanel()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		titleLabel = new javax.swing.JLabel();
		genomeLabel = new javax.swing.JLabel();
		chromoLabel = new javax.swing.JLabel();
		regionStartLabel = new javax.swing.JLabel();
		regionEndLabel = new javax.swing.JLabel();
		numberFeaturesLabel = new javax.swing.JLabel();
		showLabelsCheckbox = new javax.swing.JCheckBox();
		showHomologsCheckbox = new javax.swing.JCheckBox();
		
		titleLabel.setText("<html><b>Highlighted region:</b></html>");
		
		genomeLabel.setText("Genome:");
		
		chromoLabel.setText("Chromosome:");
		
		regionStartLabel.setText("Region start:");
		
		regionEndLabel.setText("Region end:");
		
		numberFeaturesLabel.setText("No. of features:");
		
		showLabelsCheckbox.setText("Show labels");
		showLabelsCheckbox.addChangeListener(new javax.swing.event.ChangeListener()
		{
			public void stateChanged(javax.swing.event.ChangeEvent evt)
			{
				showLabelsCheckboxStateChanged(evt);
			}
		});
		
		showHomologsCheckbox.setText("Show homologies");
		showHomologsCheckbox.addChangeListener(new javax.swing.event.ChangeListener()
		{
			public void stateChanged(javax.swing.event.ChangeEvent evt)
			{
				showHomologsCheckboxStateChanged(evt);
			}
		});
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(titleLabel).add(genomeLabel).add(chromoLabel).add(regionStartLabel).add(regionEndLabel).add(numberFeaturesLabel).add(showLabelsCheckbox).add(showHomologsCheckbox)).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(layout.createSequentialGroup().addContainerGap().add(titleLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(genomeLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(chromoLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(regionStartLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(regionEndLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(numberFeaturesLabel).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(showLabelsCheckbox).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(showHomologsCheckbox).addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents
	
	private void showHomologsCheckboxStateChanged(javax.swing.event.ChangeEvent evt)
	{
		//		System.out.println("showHomologsCheckboxStateChanged");
		MapViewer.winMain.mainCanvas.updateCanvas(true);
	}
	
	private void showLabelsCheckboxStateChanged(javax.swing.event.ChangeEvent evt)
	{
		//		System.out.println("showLabelsCheckboxStateChanged");
		MapViewer.winMain.mainCanvas.updateCanvas(true);
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel chromoLabel;
	private javax.swing.JLabel genomeLabel;
	private javax.swing.JLabel numberFeaturesLabel;
	private javax.swing.JLabel regionEndLabel;
	private javax.swing.JLabel regionStartLabel;
	private javax.swing.JCheckBox showHomologsCheckbox;
	private javax.swing.JCheckBox showLabelsCheckbox;
	private javax.swing.JLabel titleLabel;
	
	// End of variables declaration//GEN-END:variables
	public javax.swing.JLabel getChromoLabel()
	{
		return chromoLabel;
	}
	
	public javax.swing.JLabel getGenomeLabel()
	{
		return genomeLabel;
	}
	
	public javax.swing.JLabel getNumberFeaturesLabel()
	{
		return numberFeaturesLabel;
	}
	
	public javax.swing.JLabel getRegionEndLabel()
	{
		return regionEndLabel;
	}
	
	public javax.swing.JLabel getRegionStartLabel()
	{
		return regionStartLabel;
	}
	
	public javax.swing.JCheckBox getShowHomologsCheckbox()
	{
		return showHomologsCheckbox;
	}
	
	public javax.swing.JCheckBox getShowLabelsCheckbox()
	{
		return showLabelsCheckbox;
	}
	
}
