/*
 * MTFindFeaturesPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.dialog;

import javax.swing.*;

/**
 *
 * @author  __USER__
 */
public class MTFindFeaturesPanel extends javax.swing.JPanel
{
	
	/** Creates new form MTFindFeaturesPanel */
	public MTFindFeaturesPanel()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ffTextArea = new javax.swing.JTextArea();
		
		jLabel1.setText("Enter one or more feature names (one per line) you would like to highlight:");
		
		ffTextArea.setColumns(20);
		ffTextArea.setRows(5);
		ffTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
		jScrollPane1.setViewportView(ffTextArea);
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														jScrollPane1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														357,
														Short.MAX_VALUE).add(
														jLabel1)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(jLabel1).add(17,
										17, 17).add(
										jScrollPane1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										149, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextArea ffTextArea;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	
	// End of variables declaration//GEN-END:variables
	
	public JTextArea getFFTextArea()
	{
		return ffTextArea;
	}
	
}
