/*
 * GUIWidgetPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.tests.mainGui;

/**
 *
 * @author  __USER__
 */
public class GUIWidgetPanel extends javax.swing.JPanel
{
	
	MapViewerFrame frame;
	
	/** Creates new form GUIWidgetPanel */
	public GUIWidgetPanel(MapViewerFrame frame)
	{
		this.frame = frame;
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jPanel1 = new javax.swing.JPanel();
		resetZoomLeftButton = new javax.swing.JButton();
		resetZoomRightButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jTextArea1 = new javax.swing.JTextArea();
		
		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls:"));
		
		resetZoomLeftButton.setText("Reset zoom left");
		resetZoomLeftButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				resetZoomLeftButtonActionPerformed(evt);
			}
		});
		
		resetZoomRightButton.setText("Reset zoom right");
		resetZoomRightButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				resetZoomRightButtonActionPerformed(evt);
			}
		});
		
		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						org.jdesktop.layout.GroupLayout.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap().add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														resetZoomRightButton,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														resetZoomLeftButton,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														113,
														Short.MAX_VALUE)).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout.createSequentialGroup().add(resetZoomLeftButton).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										resetZoomRightButton).addContainerGap(
										70, Short.MAX_VALUE)));
		
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Locus annotation:"));
		
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setAutoscrolls(false);
		
		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(jTextArea1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(jTextArea1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE));
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														jPanel2,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														jPanel1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										jPanel1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jPanel2,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	private void resetZoomRightButtonActionPerformed(java.awt.event.ActionEvent evt)
	{
		frame.canvas2D.resetZoomFactor(1);
	}
	
	private void resetZoomLeftButtonActionPerformed(java.awt.event.ActionEvent evt)
	{
		frame.canvas2D.resetZoomFactor(0);
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JButton resetZoomLeftButton;
	private javax.swing.JButton resetZoomRightButton;
	// End of variables declaration//GEN-END:variables
	
}
