/*
 * AnnotationPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui;

import javax.swing.border.*;

import sbrn.mapviewer.data.*;
import sbrn.mapviewer.gui.entities.*;

/**
 *
 * @author  __USER__
 */
public class AnnotationPanel extends javax.swing.JPanel
{
	WinMain winMain;
	MapSet mapSet;
	
	/** Creates new form AnnotationPanel */
	public AnnotationPanel(WinMain winMain, MapSet mapSet)
	{
		this.winMain = winMain;
		this.mapSet = mapSet;
		initComponents();
		setInitialText();
		annotationTextArea.setBorder(new EmptyBorder(0, 0, 0, 0));
	}
	
	private void setInitialText()
	{
		genomeInfo.setText(mapSet.getName());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jPanel1 = new javax.swing.JPanel();
		genomeLabel = new javax.swing.JLabel();
		locusLabel = new javax.swing.JLabel();
		infoLabel = new javax.swing.JLabel();
		genomeInfo = new javax.swing.JLabel();
		locusInfo = new javax.swing.JLabel();
		annotationTextArea = new javax.swing.JTextArea();
		
		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info:"));
		
		genomeLabel.setFont(new java.awt.Font("Tahoma", 1, 13));
		genomeLabel.setText("Genome:");
		
		locusLabel.setFont(new java.awt.Font("Tahoma", 0, 13));
		locusLabel.setText("Locus:");
		
		infoLabel.setFont(new java.awt.Font("Tahoma", 0, 13));
		infoLabel.setText("Info:");
		
		genomeInfo.setFont(new java.awt.Font("Tahoma", 1, 13));
		
		locusInfo.setFont(new java.awt.Font("Tahoma", 0, 13));
		
		annotationTextArea.setBackground(new java.awt.Color(224, 223, 227));
		annotationTextArea.setColumns(20);
		annotationTextArea.setEditable(false);
		annotationTextArea.setFont(new java.awt.Font("Tahoma", 0, 13));
		annotationTextArea.setLineWrap(true);
		annotationTextArea.setRows(5);
		annotationTextArea.setWrapStyleWord(true);
		annotationTextArea.setBorder(null);
		annotationTextArea.setDisabledTextColor(new java.awt.Color(224, 223, 227));
		
		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						org.jdesktop.layout.GroupLayout.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap().add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														jPanel1Layout.createSequentialGroup().add(
																		jPanel1Layout.createParallelGroup(
																						org.jdesktop.layout.GroupLayout.LEADING).add(
																						infoLabel).add(
																						genomeLabel)).addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED).add(
																		jPanel1Layout.createParallelGroup(
																						org.jdesktop.layout.GroupLayout.LEADING).add(
																						annotationTextArea).add(
																						locusInfo,
																						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																						294,
																						Short.MAX_VALUE).add(
																						genomeInfo,
																						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																						294,
																						Short.MAX_VALUE))).add(
														locusLabel)).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout.createSequentialGroup().add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE).add(
														genomeLabel).add(
														genomeInfo,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														16,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE).add(
														locusLabel).add(
														locusInfo,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														17,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														infoLabel).add(
														annotationTextArea,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														37,
														Short.MAX_VALUE)).addContainerGap()));
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										jPanel1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().add(
										jPanel1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextArea annotationTextArea;
	private javax.swing.JLabel genomeInfo;
	private javax.swing.JLabel genomeLabel;
	private javax.swing.JLabel infoLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel locusInfo;
	private javax.swing.JLabel locusLabel;
	
	// End of variables declaration//GEN-END:variables
	
	public javax.swing.JTextArea getAnnotationTextArea()
	{
		return annotationTextArea;
	}
	
	public javax.swing.JLabel getGenomeInfo()
	{
		return genomeInfo;
	}
	
	public javax.swing.JLabel getLocusInfo()
	{
		return locusInfo;
	}
	
}
