/*
 * ControlPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.*;
import javax.swing.*;

/**
 *
 * @author  __USER__
 */
public class ControlPanel extends javax.swing.JPanel implements ItemListener
{

	WinMain winMain;
	public double blastThreshold = 1;

	/** Creates new form ControlPanel */
	public ControlPanel(WinMain winMain)
	{
		this.winMain = winMain;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jSeparator2 = new javax.swing.JSeparator();
		jPanel1 = new javax.swing.JPanel();
		antialiasCheckbox = new javax.swing.JCheckBox();
		jLabel2 = new javax.swing.JLabel();
		eValueSlider = new javax.swing.JSlider();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		blastScoreLabel = new javax.swing.JLabel();

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls:"));

		antialiasCheckbox.setText("Line smoothing");
		antialiasCheckbox.addItemListener(new java.awt.event.ItemListener()
		{
			public void itemStateChanged(java.awt.event.ItemEvent evt)
			{
				ControlPanel.this.itemStateChanged(evt);
			}
		});

		jLabel2.setText("BLAST e-value cut-off (1.00E-):");

		eValueSlider.setMajorTickSpacing(100);
		eValueSlider.setMaximum(300);
		eValueSlider.setMinorTickSpacing(50);
		eValueSlider.setPaintLabels(true);
		eValueSlider.setPaintTicks(true);
		eValueSlider.setValue(0);
		eValueSlider.addChangeListener(new javax.swing.event.ChangeListener()
		{
			public void stateChanged(javax.swing.event.ChangeEvent evt)
			{
				eValueSliderStateChanged(evt);
			}
		});

		blastScoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		blastScoreLabel.setText("Current value:                             ");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout.createSequentialGroup().add(5, 5, 5).add(
										eValueSlider,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										192, Short.MAX_VALUE)).add(
						jPanel1Layout.createSequentialGroup().addContainerGap().add(
										jPanel1Layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														jSeparator4,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														177,
														Short.MAX_VALUE).add(
														blastScoreLabel).add(
														antialiasCheckbox)).addContainerGap()).add(
						jPanel1Layout.createSequentialGroup().addContainerGap().add(
										jSeparator3,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										172, Short.MAX_VALUE).add(15, 15, 15)).add(
						jPanel1Layout.createSequentialGroup().addContainerGap().add(
										jLabel2,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										172, Short.MAX_VALUE).add(15, 15, 15)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
						org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout.createSequentialGroup().add(antialiasCheckbox).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED).add(
										jSeparator3,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										12,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
										1, 1, 1).add(jLabel2).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED).add(
										eValueSlider,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										blastScoreLabel,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										14,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(
										11, 11, 11).add(
										jSeparator4,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										10,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(
										152, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										jPanel1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										jPanel1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void eValueSliderStateChanged(javax.swing.event.ChangeEvent e)
	{
		JSlider source = (JSlider) e.getSource();

		//convert the value selected to the exponent of a small decimal and set this as
		//the new BLAST threshold (which is a double)
		int exponent = source.getValue();
		DecimalFormat df = new DecimalFormat("0.##E0");
		try
		{
			Number score = df.parse("1.00E-" + exponent);
			blastThreshold = score.doubleValue();
			blastScoreLabel.setText("Current value: " + blastThreshold);
			//			blastScoreLabel.setText("Current value: " + Math.random());
			winMain.mainCanvas.updateCanvas(true);
		}
		catch (ParseException e1)
		{
			e1.printStackTrace();
		}

	}

	public void itemStateChanged(ItemEvent e)
	{
		if (e.getItemSelectable() == antialiasCheckbox)
		{
			if (e.getStateChange() == ItemEvent.SELECTED)
			{
				winMain.mainCanvas.antiAlias = true;
			}
			else
			{
				winMain.mainCanvas.antiAlias = false;
			}
			winMain.mainCanvas.updateCanvas(true);
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JCheckBox antialiasCheckbox;
	private javax.swing.JLabel blastScoreLabel;
	private javax.swing.JSlider eValueSlider;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	// End of variables declaration//GEN-END:variables

}
