/*
 * FoundFeaturesTableControlPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.components;

/**
 *
 * @author  __USER__
 */
public class FoundFeaturesTableControlPanel extends javax.swing.JPanel
{
	
	/** Creates new form FoundFeaturesTableControlPanel */
	public FoundFeaturesTableControlPanel()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		showLabelsCheckbox = new javax.swing.JCheckBox();
		showHomologsCheckbox = new javax.swing.JCheckBox();
		
		jLabel1.setText("<html><b>Highlighted region:</b></html>");
		
		jLabel2.setText("Genome:");
		
		jLabel3.setText("Chromosome:");
		
		jLabel4.setText("Region start:");
		
		jLabel5.setText("Region end:");
		
		jLabel6.setText("No. of features:");
		
		showLabelsCheckbox.setText("Show labels");
		showLabelsCheckbox.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				showLabelsCheckboxActionPerformed(evt);
			}
		});
		
		showHomologsCheckbox.setText("Show homologs");
		showHomologsCheckbox.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				showHomologsCheckboxActionPerformed(evt);
			}
		});
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														jLabel1).add(
														jLabel2).add(
														jLabel3).add(
														jLabel4).add(
														jLabel5).add(
														jLabel6).add(
														showLabelsCheckbox).add(
														showHomologsCheckbox)).addContainerGap(
										65, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(jLabel1).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED).add(
										jLabel2).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jLabel3).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jLabel4).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jLabel5).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jLabel6).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										showLabelsCheckbox).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										showHomologsCheckbox).addContainerGap(
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents
	
	private void showHomologsCheckboxActionPerformed(java.awt.event.ActionEvent evt)
	{
		// TODO add your handling code here:
	}
	
	private void showLabelsCheckboxActionPerformed(java.awt.event.ActionEvent evt)
	{
		// TODO add your handling code here:
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JCheckBox showHomologsCheckbox;
	private javax.swing.JCheckBox showLabelsCheckbox;
	// End of variables declaration//GEN-END:variables
	
}
