// Copyright 2009 Plant Bioinformatics Group, SCRI. All rights reserved.
// Use is subject to the accompanying licence terms.

package sbrn.mapviewer.gui.components;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.*;
import sbrn.mapviewer.*;
import sbrn.mapviewer.gui.*;
import scri.commons.gui.Icons;
import scri.commons.gui.matisse.HyperLinkLabel;

public class NBStartHelpPanel extends javax.swing.JPanel implements ActionListener
{

	int numHelpLinks = 8;

	private final HyperLinkLabel[] labels = new HyperLinkLabel[numHelpLinks];

	public NBStartHelpPanel()
	{
		initComponents();
		setOpaque(false);

		homeLabel.setText("Strudel homepage");
		homeLabel.setIcon(Icons.getIcon("BOOK"));
		homeLabel.addActionListener(this);

		labels[0] = link1;
		labels[1] = link2;
		labels[2] = link3;
		labels[3] = link4;
		labels[4] = link5;
		labels[5] = link6;
		labels[6] = link7;
		labels[7] = link8;

		int numHelpLinks = calcNumHelpLinks();

		for (int i = 0; i < labels.length; i++)
		{
			if(i < numHelpLinks)
			{
				labels[i].setText(Constants.helpLabels[i]);
				labels[i].addActionListener(this);
			}
			else
			{
				labels[i].setVisible(false);
			}
		}
	}

	private int calcNumHelpLinks()
	{
		int index = 0;
		try
		{
			Class<?> constants = Class.forName("sbrn.mapviewer.Constants");
			Field field = null;

			field = constants.getField("manual" + index);
			while(field != null)
			{
				index++;
				field = constants.getField("manual" + index);
			}
		}
		catch (Exception e)
		{
		}
		return index;
	}

	public void actionPerformed(ActionEvent e)
	{
		if (e.getSource() == homeLabel)
		{
			Utils.visitURL(Constants.strudelHomePage);
		}
		else
		{
			for (int i = 0; i < labels.length; i++)
				if (e.getSource() == labels[i])
				{
					try
					{
						//the help URLs are stored in the Constants class as public members starting with "manual" and then a number
						//get the field itself and extract the respective value
						Class<?> constants = Class.forName("sbrn.mapviewer.Constants");
						Field field = constants.getField("manual" + i);
						Utils.visitURL((String)field.get(null));
					}
					catch (Exception ex)
					{
						ex.printStackTrace();
					}
				}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		homeLabel = new scri.commons.gui.matisse.HyperLinkLabel();
		link1 = new scri.commons.gui.matisse.HyperLinkLabel();
		link2 = new scri.commons.gui.matisse.HyperLinkLabel();
		link3 = new scri.commons.gui.matisse.HyperLinkLabel();
		link4 = new scri.commons.gui.matisse.HyperLinkLabel();
		link5 = new scri.commons.gui.matisse.HyperLinkLabel();
		link6 = new scri.commons.gui.matisse.HyperLinkLabel();
		link7 = new scri.commons.gui.matisse.HyperLinkLabel();
		link8 = new scri.commons.gui.matisse.HyperLinkLabel();

		homeLabel.setForeground(new java.awt.Color(68, 106, 156));
		homeLabel.setText("Strudel homepage");

		link1.setForeground(new java.awt.Color(68, 106, 156));
		link1.setIcon(Icons.getIcon("BUTTON"));
		link1.setText("link1");

		link2.setForeground(new java.awt.Color(68, 106, 156));
		link2.setIcon(Icons.getIcon("BUTTON"));
		link2.setText("link2");

		link3.setForeground(new java.awt.Color(68, 106, 156));
		link3.setIcon(Icons.getIcon("BUTTON"));
		link3.setText("link3");

		link4.setForeground(new java.awt.Color(68, 106, 156));
		link4.setIcon(Icons.getIcon("BUTTON"));
		link4.setText("link4");

		link5.setForeground(new java.awt.Color(68, 106, 156));
		link5.setIcon(Icons.getIcon("BUTTON"));
		link5.setText("link5");

		link6.setForeground(new java.awt.Color(68, 106, 156));
		link6.setIcon(Icons.getIcon("BUTTON"));
		link6.setText("link6");

		link7.setForeground(new java.awt.Color(68, 106, 156));
		link7.setIcon(Icons.getIcon("BUTTON"));
		link7.setText("link7");

		link8.setForeground(new java.awt.Color(68, 106, 156));
		link8.setIcon(Icons.getIcon("BUTTON"));
		link8.setText("link8");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(link8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(113, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(link1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(link2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(6, 6, 6).addComponent(link3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(6, 6, 6).addComponent(link4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(6, 6, 6).addComponent(link5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(6, 6, 6).addComponent(link6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(link7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(link8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private scri.commons.gui.matisse.HyperLinkLabel homeLabel;
	private scri.commons.gui.matisse.HyperLinkLabel link1;
	private scri.commons.gui.matisse.HyperLinkLabel link2;
	private scri.commons.gui.matisse.HyperLinkLabel link3;
	private scri.commons.gui.matisse.HyperLinkLabel link4;
	private scri.commons.gui.matisse.HyperLinkLabel link5;
	private scri.commons.gui.matisse.HyperLinkLabel link6;
	private scri.commons.gui.matisse.HyperLinkLabel link7;
	private scri.commons.gui.matisse.HyperLinkLabel link8;
	// End of variables declaration//GEN-END:variables

}
