/*
 * AnnotationPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui;

import javax.swing.border.*;

import sbrn.mapviewer.data.*;
import sbrn.mapviewer.gui.entities.*;

/**
 *
 * @author  __USER__
 */
public class AnnotationPanel extends javax.swing.JPanel
{
	WinMain winMain;
	MapSet mapSet;
	
	/** Creates new form AnnotationPanel */
	public AnnotationPanel(WinMain winMain, MapSet mapSet)
	{
		this.winMain = winMain;
		this.mapSet = mapSet;
		initComponents();
		setInitialText();
		annotationTextArea.setBorder(new EmptyBorder(0, 0, 0, 0));
	}
	
	private void setInitialText()
	{
		genomeInfo.setText(mapSet.getName());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		genomeLabel = new javax.swing.JLabel();
		locusLabel = new javax.swing.JLabel();
		infoLabel = new javax.swing.JLabel();
		genomeInfo = new javax.swing.JLabel();
		locusInfo = new javax.swing.JLabel();
		annotationTextArea = new javax.swing.JTextArea();
		
		genomeLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
		genomeLabel.setText("Genome:");
		
		locusLabel.setText("Locus:");
		
		infoLabel.setText("Info:");
		
		genomeInfo.setFont(new java.awt.Font("Tahoma", 1, 12));
		
		annotationTextArea.setBackground(new java.awt.Color(224, 223, 227));
		annotationTextArea.setColumns(20);
		annotationTextArea.setEditable(false);
		annotationTextArea.setFont(new java.awt.Font("Tahoma", 0, 11));
		annotationTextArea.setLineWrap(true);
		annotationTextArea.setRows(5);
		annotationTextArea.setWrapStyleWord(true);
		annotationTextArea.setBorder(null);
		annotationTextArea.setDisabledTextColor(new java.awt.Color(224, 223, 227));
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														genomeLabel).add(
														locusLabel).add(
														infoLabel)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														locusInfo).add(
														genomeInfo).add(
														annotationTextArea)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE).add(
														genomeLabel).add(
														genomeInfo)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE).add(
														locusLabel).add(
														locusInfo)).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING).add(
														annotationTextArea,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														90,
														Short.MAX_VALUE).add(
														infoLabel)).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextArea annotationTextArea;
	private javax.swing.JLabel genomeInfo;
	private javax.swing.JLabel genomeLabel;
	private javax.swing.JLabel infoLabel;
	private javax.swing.JLabel locusInfo;
	private javax.swing.JLabel locusLabel;
	
	// End of variables declaration//GEN-END:variables
	
	public javax.swing.JTextArea getAnnotationTextArea()
	{
		return annotationTextArea;
	}
	
	public javax.swing.JLabel getGenomeInfo()
	{
		return genomeInfo;
	}
	
	public javax.swing.JLabel getLocusInfo()
	{
		return locusInfo;
	}
	
}
