/*
 * MTDataLoadingDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.dialog;

import sbrn.mapviewer.*;
import scri.commons.gui.*;

/**
 *
 * @author  __USER__
 */
public class MTDataLoadingDialog extends javax.swing.JDialog
{

	/** Creates new form MTDataLoadingDialog */
	public MTDataLoadingDialog(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();

		addWindowListener(new java.awt.event.WindowAdapter()
		{
			@Override
			public void windowClosing(java.awt.event.WindowEvent e)
			{
				setVisible(false);
				Strudel.winMain.fatController.dataLoadCancelled = true;
				TaskDialog.info("Data import canceled.", "Close");
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		dataLoadingLabel = new javax.swing.JLabel();
		progressBar = new javax.swing.JProgressBar();
		dataLoadcancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Data loading");

		dataLoadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		dataLoadingLabel.setText("Data loading - please wait...");
		dataLoadingLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		progressBar.setIndeterminate(true);

		dataLoadcancelButton.setText("Cancel");
		dataLoadcancelButton.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				dataLoadcancelButtonActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(
										progressBar,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										271, Short.MAX_VALUE).addContainerGap()).add(
						layout.createSequentialGroup().add(12, 12, 12).add(
										dataLoadingLabel,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										271, Short.MAX_VALUE).addContainerGap(
										12, Short.MAX_VALUE)).add(
						layout.createSequentialGroup().add(111, 111, 111).add(
										dataLoadcancelButton).addContainerGap(
										113, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(dataLoadingLabel).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED).add(
										progressBar,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED).add(
										dataLoadcancelButton).addContainerGap(
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void dataLoadcancelButtonActionPerformed(java.awt.event.ActionEvent evt)
	{
		setVisible(false);
		Strudel.winMain.fatController.dataLoadCancelled = true;
		TaskDialog.info("Data import canceled.", "Close");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				MTDataLoadingDialog dialog = new MTDataLoadingDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter()
				{
					@Override
					public void windowClosing(java.awt.event.WindowEvent e)
					{
						System.exit(0);
						TaskDialog.info("dialog closed", "Close");
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton dataLoadcancelButton;
	private javax.swing.JLabel dataLoadingLabel;
	private javax.swing.JProgressBar progressBar;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JButton getDataLoadcancelButton()
	{
		return dataLoadcancelButton;
	}

	public javax.swing.JLabel getDataLoadingLabel()
	{
		return dataLoadingLabel;
	}

}
