/*
 * MTFindFeaturesResultsPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.dialog;

import javax.swing.JList;

import sbrn.mapviewer.data.*;
import sbrn.mapviewer.gui.*;

/**
 *
 * @author  __USER__
 */
public class MTFindFeaturesResultsPanel extends javax.swing.JPanel
{
	
	/** Creates new form MTFindFeaturesResultsPanel */
	public MTFindFeaturesResultsPanel()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		ffResultsList = new javax.swing.JList();
		
		jLabel1.setText("<html>Matching features found -- click on name to highlight:</html>");
		
		ffResultsList.setBackground(new java.awt.Color(236, 233, 216));
		ffResultsList.setModel(new javax.swing.AbstractListModel()
		{
			String[] strings =
			{ "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
			
			public int getSize()
			{
				return strings.length;
			}
			
			public Object getElementAt(int i)
			{
				return strings[i];
			}
		});
		ffResultsList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
		{
			public void valueChanged(javax.swing.event.ListSelectionEvent evt)
			{
				ffResultsListValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(ffResultsList);
		
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup().addContainerGap().add(
										layout.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														jScrollPane1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														272,
														Short.MAX_VALUE).add(
														org.jdesktop.layout.GroupLayout.LEADING,
														jLabel1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														272,
														Short.MAX_VALUE)).add(
										12, 12, 12)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						layout.createSequentialGroup().addContainerGap().add(jLabel1).addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED).add(
										jScrollPane1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										266, Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents
	
	private void ffResultsListValueChanged(javax.swing.event.ListSelectionEvent evt)
	{
		if (evt.getValueIsAdjusting())
			return;
		
		//get the name of the feature the user has selected from the list of search results
		JList list = (JList) evt.getSource();
		String searchFeatureName = (String) list.getSelectedValue();
		
		//now highlight this feature and its homologs
		if (searchFeatureName != null)
			MapViewer.winMain.fatController.highlightRequestedFeature(searchFeatureName.trim());
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JList ffResultsList;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	
	// End of variables declaration//GEN-END:variables
	
	public JList getFFResultsList()
	{
		return ffResultsList;
	}
	
}
