/*
 * ExampleDataInfoPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package sbrn.mapviewer.gui.dialog;

import sbrn.mapviewer.*;

/**
 *
 * @author  __USER__
 */
public class ExampleDataInfoPanel extends javax.swing.JPanel
{

	/** Creates new form ExampleDataInfoPanel */
	public ExampleDataInfoPanel()
	{
		initComponents();

		genome1InfoLabel.setText("<html><b>Genome 1 (left):</b><br/>" + Constants.exampleGenome1Description + "</html>");
		genome2InfoLabel.setText("<html><b>Genome 2 (middle):</b><br/>" + Constants.exampleGenome2Description + "</html>");
		genome3InfoLabel.setText("<html><b>Genome 3 (right):</b><br/>" + Constants.exampleGenome3Description + "</html>");

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		genome1InfoLabel = new javax.swing.JLabel();
		genome2InfoLabel = new javax.swing.JLabel();
		genome3InfoLabel = new javax.swing.JLabel();

		genome1InfoLabel.setText("jLabel1");

		genome2InfoLabel.setText("jLabel1");

		genome3InfoLabel.setText("jLabel1");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(genome1InfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE).addComponent(genome2InfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE).addComponent(genome3InfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(genome1InfoLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(genome2InfoLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(genome3InfoLabel).addContainerGap(49, Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel genome1InfoLabel;
	private javax.swing.JLabel genome2InfoLabel;
	private javax.swing.JLabel genome3InfoLabel;
	// End of variables declaration//GEN-END:variables

}
